# Generated by Django 4.1.5 on 2023-02-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.TextField(max_length=50, verbose_name='Content'),
        ),
    ]
