# Generated by Django 4.1.5 on 2023-01-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='id_public',
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.BooleanField(choices=[('Published', 'Published'), ('Notpublished', 'Notpublished')], default='Published', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='record',
            name='slug',
            field=models.CharField(max_length=50, verbose_name='Slug'),
        ),
    ]
