# Generated by Django 4.1.5 on 2023-01-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_record_id_public_record_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={},
        ),
    ]
