# Generated by Django 4.1.5 on 2023-01-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_record_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='status',
        ),
        migrations.AddField(
            model_name='record',
            name='id_public',
            field=models.BooleanField(choices=[(True, True), (False, False)], default=True, verbose_name='Опубликовано'),
        ),
    ]
