# Generated by Django 4.1.5 on 2023-01-21 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250, verbose_name='Category')),
                ('category_description', models.CharField(max_length=250, verbose_name='Category description')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='Naimenovanie Producta')),
                ('product_description', models.CharField(max_length=250, verbose_name='Product description')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('date_last_change', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
