# Generated by Django 4.1.5 on 2023-02-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'available'), ('inactive', 'not item in list')], default='active', max_length=20),
        ),
    ]
