# Generated by Django 4.1.5 on 2023-01-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_product_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.CharField(default=3, max_length=250, verbose_name='Что-то, что мы щас удалим миграцией'),
            preserve_default=False,
        ),
    ]
