# Generated by Django 4.1.5 on 2023-01-25 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_category_alter_product_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, max_length=250, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='catalog.category', verbose_name='Category description'),
        ),
    ]
