# Generated by Django 4.1.5 on 2023-01-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField()),
                ('content', models.TextField(max_length=50, verbose_name='URL')),
                ('image', models.TextField(blank=True, null=True, verbose_name='Содержимое')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('id_public', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views_controller', models.IntegerField(default=0, verbose_name='Счетчик просмотров')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
